# Generated by Django 5.2.17 on 2026-08-16 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Shown as alt text and as a fallback label if no image is uploaded yet.', max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='promos/')),
                ('link_url', models.URLField(blank=True, help_text='Optional — where the promo should link to when clicked (e.g. an offers page or Facebook post).')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this promo from the homepage without deleting it.')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first. Promos with the same number are sorted by newest.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
