# Generated by Django 5.2.17 on 2026-08-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_promo_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='bed_configuration',
            field=models.CharField(blank=True, help_text="e.g. '1 Queen Bed, 2 Single Beds' — shown to customers on the room detail page.", max_length=150),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='extra_pax_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Charge per additional guest, per night, beyond the base capacity. Leave as 0 if this room type doesn't allow extra guests for a fee.", max_digits=8),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.PositiveIntegerField(help_text="Maximum guests included in the base price, per room of this type. Extra guests beyond this are billed at 'extra_pax_fee' each, per night."),
        ),
    ]
