# Generated by Django 5.2.17 on 2026-09-24 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_roomtype_bed_configuration_roomtype_extra_pax_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to remove this room from booking without deleting its history.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='bookings.roomtype')),
            ],
            options={
                'ordering': ['room_type', 'room_number'],
                'unique_together': {('room_type', 'room_number')},
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ManyToManyField(blank=True, help_text='Specific room(s) assigned to this reservation, matching num_rooms in count', related_name='reservations', to='bookings.room'),
        ),
    ]
