# Generated by Django 5.2.17 on 2026-09-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_room_reservation_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='size_sqm',
        ),
    ]
