# Generated by Django 5.2.17 on 2026-10-05 04:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_roomtype_size_sqm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a PH mobile number in the format +639XXXXXXXXX.', regex='^\\+639\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Enter a PH mobile number in the format +639XXXXXXXXX.', regex='^\\+639\\d{9}$')]),
        ),
    ]
